build:
	docker build -t pl_frontend .

up:
	docker-compose -p travel_management_fe up

down:
	docker-compose -p travel_management_fe down

restart:
	docker-compose -p travel_management_fe down
	docker-compose -p travel_management_fe up