# Generated by Django 3.2.4 on 2021-12-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_location_groupjourney_location'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupcustomer',
            unique_together={('group', 'customer')},
        ),
    ]
