# Generated by Django 3.2.4 on 2021-10-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('Aboard', 'Aboard'), ('Domestic', 'Domestic'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TourCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourcharacteristic')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.location')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourprice')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourtype')),
            ],
        ),
    ]
