# Generated by Django 3.2.4 on 2021-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('District', 'District'), ('City', 'City'), ('Province', 'Province'), ('Country', 'Country'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('Tourist Area', 'Tourist Area'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
