# Generated by Django 3.2.4 on 2021-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20211022_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Tourist Area', 'Tourist Area'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
