# Generated by Django 3.2.4 on 2021-11-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_location_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tourcharacteristic',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tourprice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'ordering': ['id']},
        ),
    ]
