# Generated by Django 3.2.4 on 2021-12-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20211103_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
