# Generated by Django 3.2.4 on 2021-10-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupjourney',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupjourney',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
