# Generated by Django 3.2.4 on 2021-10-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20211022_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupjourney',
            old_name='Location',
            new_name='location',
        ),
    ]
