# Generated by Django 3.2.4 on 2021-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_groupjourneycost_groupjourneycosttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjourneycost',
            name='group_journey',
        ),
        migrations.AddField(
            model_name='groupjourneycost',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
