# Generated by Django 3.2.4 on 2021-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20211206_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupjourneycost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
